services:
  taskmanager.api:
    image: taskmanager.api
    build:
      context: .
      dockerfile: TaskManager.API/Dockerfile

  taskmanager.dal:
    image: taskmanager.dal
    build:
      context: .
      dockerfile: TaskManager.DAL/Dockerfile

